'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Raven.Web.Secure.Incl

    Partial Public Class SearchList

        '''<summary>
        '''frmInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmInfo As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''lblSearchList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSearchList As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSearchResults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSearchResults As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlFilterBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlFilterBy As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtFilterBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFilterBy As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnApplyFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnApplyFilter As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''lblSearchProcedure control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSearchProcedure As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtSearchCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSearchCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''grdSearchList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdSearchList As Global.System.Web.UI.WebControls.DataGrid
    End Class
End Namespace
